project_id = "exhdkdlgezoqfrvhbwww"

[functions.livestock-care-suggestions]
verify_jwt = false

[functions.increment-batch-age]
verify_jwt = false

[functions.clinic-ai-suggestions]
verify_jwt = false

[functions.farm-ai-chat]
verify_jwt = false
