import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { FileText, Download, Search } from "lucide-react";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { toast } from "sonner";
import { useBranch } from "@/contexts/BranchContext";
import { format } from "date-fns";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const InvoiceGenerator = () => {
  const { currentBranchId } = useBranch();
  const [sales, setSales] = useState<any[]>([]);
  const [buyerFilter, setBuyerFilter] = useState("");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");
  const [loading, setLoading] = useState(false);

  const searchSales = async () => {
    setLoading(true);
    let query = supabase
      .from("sales_records")
      .select("*, customers(name, phone, address)")
      .order("date", { ascending: false });

    if (currentBranchId) query = query.eq("branch_id", currentBranchId);
    if (buyerFilter) query = query.ilike("buyer_name", `%${buyerFilter}%`);
    if (dateFrom) query = query.gte("date", dateFrom);
    if (dateTo) query = query.lte("date", dateTo);

    const { data } = await query;
    setSales(data || []);
    setLoading(false);
  };

  const generateInvoice = (selectedSales: any[]) => {
    if (selectedSales.length === 0) {
      toast.error("No sales selected");
      return;
    }

    const doc = new jsPDF();
    const buyerName = selectedSales[0].buyer_name || selectedSales[0].customers?.name || "Customer";
    const invoiceNo = `INV-${Date.now().toString(36).toUpperCase()}`;

    // Header
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text("AGROCREST FARM", 105, 20, { align: "center" });
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Farm Management System", 105, 27, { align: "center" });

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("INVOICE", 105, 40, { align: "center" });

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Invoice #: ${invoiceNo}`, 14, 50);
    doc.text(`Date: ${format(new Date(), "MMMM dd, yyyy")}`, 14, 56);
    doc.text(`Customer: ${buyerName}`, 14, 62);

    const customer = selectedSales[0].customers;
    if (customer) {
      if (customer.phone) doc.text(`Phone: ${customer.phone}`, 14, 68);
      if (customer.address) doc.text(`Address: ${customer.address}`, 14, 74);
    }

    // Items table
    const tableData = selectedSales.map((s) => [
      format(new Date(s.date), "MMM dd, yyyy"),
      s.product_name,
      `${s.quantity} ${s.unit}`,
      `₦${Number(s.price_per_unit).toLocaleString()}`,
      `₦${Number(s.total_amount).toLocaleString()}`,
      s.payment_status,
    ]);

    const totalAmount = selectedSales.reduce((s, r) => s + Number(r.total_amount), 0);
    const totalPaid = selectedSales.reduce((s, r) => s + Number(r.amount_paid), 0);
    const balance = totalAmount - totalPaid;

    autoTable(doc, {
      startY: customer?.address ? 80 : 70,
      head: [["Date", "Product", "Qty", "Unit Price", "Total", "Status"]],
      body: tableData,
      theme: "grid",
      headStyles: { fillColor: [34, 139, 34] },
    });

    const finalY = (doc as any).lastAutoTable.finalY + 10;
    doc.setFont("helvetica", "bold");
    doc.text(`Total: ₦${totalAmount.toLocaleString()}`, 140, finalY);
    doc.text(`Paid: ₦${totalPaid.toLocaleString()}`, 140, finalY + 7);
    if (balance > 0) {
      doc.setTextColor(255, 0, 0);
      doc.text(`Balance: ₦${balance.toLocaleString()}`, 140, finalY + 14);
      doc.setTextColor(0, 0, 0);
    }

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text("Thank you for your patronage!", 105, finalY + 28, { align: "center" });
    doc.text("Generated by Agrocrest Farm Management System", 105, finalY + 33, { align: "center" });

    doc.save(`Invoice_${buyerName.replace(/\s+/g, "_")}_${invoiceNo}.pdf`);
    toast.success("Invoice generated!");
  };

  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());

  const toggleSelect = (id: string) => {
    const newSet = new Set(selectedIds);
    if (newSet.has(id)) newSet.delete(id);
    else newSet.add(id);
    setSelectedIds(newSet);
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-base flex items-center gap-2">
          <FileText className="h-5 w-5 text-primary" />
          Invoice Generator
        </CardTitle>
        <CardDescription>Generate PDF invoices from sales records</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid grid-cols-1 sm:grid-cols-4 gap-3">
          <div>
            <Label className="text-xs">Customer Name</Label>
            <Input
              placeholder="Search customer..."
              value={buyerFilter}
              onChange={(e) => setBuyerFilter(e.target.value)}
            />
          </div>
          <div>
            <Label className="text-xs">From Date</Label>
            <Input type="date" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} />
          </div>
          <div>
            <Label className="text-xs">To Date</Label>
            <Input type="date" value={dateTo} onChange={(e) => setDateTo(e.target.value)} />
          </div>
          <div className="flex items-end">
            <Button onClick={searchSales} disabled={loading} className="w-full">
              <Search className="h-4 w-4 mr-2" /> Search
            </Button>
          </div>
        </div>

        {sales.length > 0 && (
          <>
            <div className="flex items-center justify-between">
              <span className="text-sm text-muted-foreground">{sales.length} records found</span>
              <Button
                size="sm"
                onClick={() => generateInvoice(sales.filter((s) => selectedIds.has(s.id)))}
                disabled={selectedIds.size === 0}
              >
                <Download className="h-4 w-4 mr-2" />
                Generate Invoice ({selectedIds.size})
              </Button>
            </div>
            <div className="overflow-x-auto max-h-64 overflow-y-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="w-10">✓</TableHead>
                    <TableHead>Date</TableHead>
                    <TableHead>Product</TableHead>
                    <TableHead>Buyer</TableHead>
                    <TableHead className="text-right">Amount</TableHead>
                    <TableHead>Status</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {sales.map((s) => (
                    <TableRow key={s.id} className="cursor-pointer" onClick={() => toggleSelect(s.id)}>
                      <TableCell>
                        <input type="checkbox" checked={selectedIds.has(s.id)} onChange={() => toggleSelect(s.id)} />
                      </TableCell>
                      <TableCell className="text-sm">{format(new Date(s.date), "MMM dd")}</TableCell>
                      <TableCell className="text-sm">{s.product_name}</TableCell>
                      <TableCell className="text-sm">{s.buyer_name || "-"}</TableCell>
                      <TableCell className="text-sm text-right font-medium">₦{Number(s.total_amount).toLocaleString()}</TableCell>
                      <TableCell>
                        <Badge variant="outline" className="text-xs">
                          {s.payment_status}
                        </Badge>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          </>
        )}
      </CardContent>
    </Card>
  );
};

export default InvoiceGenerator;
